// src/documents/enums/document-type.enum.ts
export enum DocumentType {
  PATIENT_LIST = 'PATIENT_LIST',
  CLINIC_LIST = 'CLINIC_LIST',
  PSYCHOLOGIST_LIST = 'PSYCHOLOGIST_LIST',
  FINANCIAL_REPORT = 'FINANCIAL_REPORT',
  MOOD_DIARY_REPORT = 'MOOD_DIARY_REPORT',
  APPOINTMENT_HISTORY = 'APPOINTMENT_HISTORY',
  PATIENT_CARD = 'PATIENT_CARD',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  DECLARATION_OF_SERVICE = 'DECLARATION_OF_SERVICE',
}
